In [3]:
import numpy as np 

In [6]:
vector_row = ([1, 2, 3])

In [7]:
vector_column = ([[1], [2], [3]])

In [8]:
vector_row

[1, 2, 3]

In [9]:
vector_column


[[1], [2], [3]]

In [10]:
matrix = np.array([[1, 2], 
                   [1, 2],
                   [1, 2]])

In [11]:
matrix

array([[1, 2],
       [1, 2],
       [1, 2]])

In [12]:
matrix_object = np.mat([[1, 2],
                        [1, 2],
                        [1, 2]])

In [16]:
matrix_object

matrix([[1, 2],
        [1, 2],
        [1, 2]])

In [17]:
from scipy import sparse 

In [18]:
matrix = np.array([[0, 0],
                   [0, 1],
                   [3, 0]])

In [19]:
matrix

array([[0, 0],
       [0, 1],
       [3, 0]])

In [21]:
matrix_sparse = sparse.csr_matrix(matrix)

In [22]:
matrix_sparse

<3x2 sparse matrix of type '<class 'numpy.int32'>'
	with 2 stored elements in Compressed Sparse Row format>

In [23]:
print(matrix_sparse)

  (1, 1)	1
  (2, 0)	3


In [24]:
matrix_large = np.array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                         [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
                         [3, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

matrix_large_sparse = sparse.csr_matrix(matrix_large)

In [25]:
print(matrix_sparse)

  (1, 1)	1
  (2, 0)	3


In [26]:
print(matrix_large_sparse)

  (1, 1)	1
  (2, 0)	3


In [27]:
vector = np.array([1, 2, 3, 4, 5, 6])

In [4]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

In [29]:
vector[2]

3

In [30]:
matrix[1,1]

5

In [31]:
vector[:]

array([1, 2, 3, 4, 5, 6])

In [32]:
vector[:3]

array([1, 2, 3])

In [33]:
vector[3:]

array([4, 5, 6])

In [34]:
vector[-1]

6

In [35]:
matrix[:2, :]

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
matrix[0:3,1:2]

array([[2],
       [5],
       [8]])

In [39]:
matrix = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12]])

In [40]:
matrix.shape

(3, 4)

In [41]:
matrix.size

12

In [42]:
matrix.ndim

2

In [43]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

In [17]:
matrix [0:1, 0:1]

array([[1]])